### ISSUE TITLE
Add "Dates & Calendars" category?

### ISSUE THREAD

**Issue by deanishe** [alfred-workflows/awesome-alfred-workflows#48]
There are several very useful workflows in this category, some of them already elsewhere in the list.

What do you think of creating this (or similar) category? Have any nominations to make it worthwhile?

**Comment by derimagia** [comment]
I think this is a good idea. Do you have any recommendations? I looked through @nikitavoloboev's list and only saw a few

**Comment by deanishe** [comment]
There are only a couple of workflows already in the list, but there are others out there.

There are several workflows for calculating relative dates (including one I wrote), but perhaps more interestingly, for any give calendar app that supports natural-language input, there's a corresponding workflow.

Technically-speaking, most are nothing to write home about, but if you're a big fan of, say, Fantastical, it's bloody awesome to be able to enter your appointments via Alfred.

**Comment by derimagia** [comment]
Candidates so far (gonna do more research and filter these down):

Calculating Dates:
* https://github.com/deanishe/alfred-relative-dates
* https://github.com/perfectworks/alfred-workflow-moment
* http://www.packal.org/workflow/timestamp 

Calendar:
* https://github.com/owenwater/alfred-cal
* https://github.com/deanishe/alfred-gcal (Already on list)

Fantastical: (Note: I currently don't use fantastical)
* https://github.com/robb/Fantastical-Alfred-Workflow
* http://www.packal.org/workflow/fantastical-apple-calendar 

Also.. sigh, 
_shakes fist at packal.org_: http://www.packal.org/search/site/Timestamp

**Comment by nikitavoloboev** [comment]
Is amazing too: https://github.com/lox/alfred-timezone

**Comment by vitorgalvao** [comment]
Will accept a PR which adds the category and Workflows. No Python 2 Workflows, please.
