### ISSUE TITLE
Add "moment"?

### ISSUE THREAD

**Issue by e7h4n** [alfred-workflows/awesome-alfred-workflows#52]
moment (https://github.com/perfectworks/alfred-workflow-moment) is a time utility. It can convert time format between timestamp and time string, operate time and date.

![moment start of year](https://raw.githubusercontent.com/perfectworks/screenshots/master/moment4.png)

![combination of commands](https://raw.githubusercontent.com/perfectworks/screenshots/master/moment6.png)

**Comment by deanishe** [comment]
Related to #48.

@perfectworks: Could you [submit a PR with the corresponding changes](https://github.com/derimagia/awesome-alfred-workflows/blob/master/CONTRIBUTING.md)?

**Comment by vitorgalvao** [comment]
Closing because it is a Python 2 Workflow. Will reconsider inclusion if updated to Python 3 or another language.
