### ISSUE TITLE
Link for Alfredworkflow.com redirect to another website

### ISSUE THREAD

**Issue by danickblouin** [alfred-workflows/awesome-alfred-workflows#86]
It seems like the URL for [Alfredworkflow](https://alfredworkflow.com) redirects to [MenuBarX](https://menubarx.app/), a menu bar app that has nothing to do with Alfred.
In [other lists](https://github.com/alfred-workflows/awesome-alfred-workflows#other-lists) section

**Comment by vitorgalvao** [comment]
Thank you for the heads-up. Removed.
